### ISSUE TITLE
Recursive pawnDeepRef causing corrupt saves

### ISSUE THREAD

**Issue by isavegas** [Ogliss/Rebelrots-Yautja-Race#20]
Something in the v1.0.0.4 update is adding a reference in pawns to themselves under `pawnDeepRef`, causing the game to recursively save the same pawn data inside itself. I ended up with save files in the 4.6GiB range. Unsure what's causing it, but reverting to the last version allowed me to resume from my last uncorrupted save.

**Comment by Ogliss** [comment]
hmmm bugger......theres 2 references to that, one in the Comp_Yautja(which controls the marking system) and on in the HediffComp_Facehugger, they were added last update, i dont really understand how the saving system works, perhaps because the node name was the same? though they were refering to different pawns, in Comp_Yautja its saving the last pawn thats been killed by the ower of the comp, and in HediffComp_Facehugger its refering to the facehugger that is attached to the pawn its parent hediff is on. i still havent managed to repo the issue locally despite spending most of yesterday doing a test playthrough, so far none of the other reports on the issue have provided any details that have helped narrow down the conditions required to create the issue. if i were to fix those references so they were unique, and push a test branch, would you be willing to give it a bash and see if it happens again?

**Comment by Ogliss** [comment]
https://github.com/Ogliss/Rebelrots-Yautja-Race/tree/Save-Corruption-Fix

if you could test that, it would be much appreciated

**Comment by isavegas** [comment]
Will do. Probably won't be til 5pm or so, though. :)

**Comment by Ogliss** [comment]
the other thing would be opening the save file with a text editior, like notepad++ and looking for the bloat,  it might even be a simple matter of deleting the bloat to fix em

**Comment by isavegas** [comment]
I'm about to do it. Ended up working way later than I expected. I did open the file with an editor (huge pain at that file size) and I deleted the references, but it didn't help. Instead of crashing while loading, it just complained that the save was broken.

**Comment by isavegas** [comment]
Yep, looks like [Save-Corruption-Fix](https://github.com/Ogliss/Rebelrots-Yautja-Race/tree/Save-Corruption-Fix) still has the issue.

**Comment by Ogliss** [comment]
huh, thats weird, cause i finally had it happen to me last night with that, ive updated the main mod both on git and steam with a fix that worked for me

**Comment by isavegas** [comment]
Alright, so the Save-Corruption-Fix branch DOES have the issue, but the version on the workshop doesn't. As the master branch must be fixed, I'd say this issue can safely be closed. Thanks!!!
